---
files:
- path: "C:/Users/brett/Documents/csharp/CS12-Dotnet8/chap13/PracticalApps/extra/style.css"
  readOnly: false
- path: "C:/Users/brett/Documents/csharp/CS12-Dotnet8/chap13/PracticalApps/extra/index.html"
  readOnly: false
