@base_address = https://localhost:5151/

GET {{{{base_address}}}}/weatherforecast/
Accept: application/json

### Get the weather forecast for a period of days
GET {{{{base_address}}}}/weatherforecast/2
Accept: application/json
